### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by kokenot** [helmiau/helmiwrt-packages#2]
hi helmi. i've got an error when compiling this source locally. 

`chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory
chmod: cannot access '/www/*': No such file or directory
chmod: cannot access '/www/libernet/*': No such file or directory
chmod: cannot access '/root/libernet/*': No such file or directory
chmod: cannot access '/root/libernet/bin/*': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory
chmod: cannot access '/etc/init.d/v2raya'$'\n\t''chmod -R 755 /etc/v2raya/web': No such file or directory
chmod: cannot access '/usr/bin/v2raya'$'\n\t''chmod -R 755 /bin/v2raya': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory
chmod: cannot access '/www/*': No such file or directory
chmod: cannot access '/www/xderm/*': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory
chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory
chmod: cannot access '/www/*': No such file or directory
chmod: cannot access '/www/xderm/*': No such file or directory
`
please help me. why this error come while finalizing compiling firmware. i already clone the source code and at the make menuconfig the app is showing in the menu

**Comment by helmiau** [comment]
> hi helmi. i've got an error when compiling this source locally.
> 
> 
```
chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory chmod: cannot access '/www/*': No such file or directory chmod: cannot access '/www/libernet/*': No such file or directory chmod: cannot access '/root/libernet/*': No such file or directory chmod: cannot access '/root/libernet/bin/*': No such file or directory chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory chmod: cannot access '/etc/init.d/v2raya'$'\n\t''chmod -R 755 /etc/v2raya/web': No such file or directory chmod: cannot access '/usr/bin/v2raya'$'\n\t''chmod -R 755 /bin/v2raya': No such file or directory chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory chmod: cannot access '/www/*': No such file or directory chmod: cannot access '/www/xderm/*': No such file or directory chmod: cannot access '/usr/lib/lua/luci/controller/*': No such file or directory chmod: cannot access '/usr/lib/lua/luci/view/*': No such file or directory chmod: cannot access '/www/*': No such file or directory chmod: cannot access '/www/xderm/*': No such file or directory 
```

> please help me. why this error come while finalizing compiling firmware. i already clone the source code and at the make menuconfig the app is showing in the menu

 have you downloaded the repo completely?

can you send me your enabled config?

**Comment by rootjack404** [comment]
Those error are normal while compiling because when finalizing the firmware it will try to run the script which included in the package. It will be fine if you manage to successfully build the rootfs and run it on your machine
