### ISSUE TITLE
libernet plus issue

### ISSUE THREAD

**Issue by kokenot** [helmiau/helmiwrt-packages#3]
hi helmi. this is new issue regarding issue of #2 i've create before. i've done installing libernet plus. i'm compiling arm v8 firmware using immortalwrt as my source. 
test my firmware and i can't see tun at my network interface. seems like creation of tun automatic script failed. i also need to run fixphp to make sure libernet plus is accessible. all the require package has been add to my config. i need your help to troubleshoot. tq helmi. thanks for your hard work.

**Comment by helmiau** [comment]
> hi helmi. this is new issue regarding issue of #2 i've create before. i've done installing libernet plus. i'm compiling arm v8 firmware using immortalwrt as my source.
> test my firmware and i can't see tun at my network interface. seems like creation of tun automatic script failed. i also need to run fixphp to make sure libernet plus is accessible. all the require package has been add to my config. i need your help to troubleshoot. tq helmi. thanks for your hard work.

is tun0 interface installed?

**Comment by kokenot** [comment]
Tun0 does not show up in network interface. I tried to manually set the tun0 but when try to use ovpn the is an error in system log show 'openvpn connection unavailable'. I check at openwrt system log error 'if config tun1 error fetching interface information : device not found

**Comment by helmiau** [comment]
using this script ? `/usr/sbin/openvpn --mktun --dev tun1`

**Comment by kokenot** [comment]
![16324911024328389109125350984718](https://user-images.githubusercontent.com/26756586/134684778-16cdf047-f204-4abe-9dfc-ac6561185a07.jpg)
![16324911893552037948561667823402](https://user-images.githubusercontent.com/26756586/134685025-8bdad10a-38ca-479b-95ae-edf6a4f30b21.jpg)

**Comment by kokenot** [comment]
> using this script ? `/usr

**Comment by kokenot** [comment]
> using this script ? `/usr/sbin/openvpn --mktun --dev tun1`

![16324913132904206093151101229430](https://user-images.githubusercontent.com/26756586/134685300-3607e999-90c4-487d-9e67-43be8a2d7cee.jpg)

**Comment by kokenot** [comment]
![1632491531075632673532870586784](https://user-images.githubusercontent.com/26756586/134685820-abcaff4b-92b5-4b3b-8ad4-798b13912341.jpg)

**Comment by rootjack404** [comment]
> > using this script ? `/usr/sbin/openvpn --mktun --dev tun1`
> 
> ![16324913132904206093151101229430](https://user-images.githubusercontent.com/26756586/134685300-3607e999-90c4-487d-9e67-43be8a2d7cee.jpg)

No this is not the correct way to use that command. Those command wasn't supposed to be in the installer/compiler script since it need openvpn to be installed at a running system. For your problem it seems the same as [https://github.com/helmiau/HelmiWrt-OS/issues/31](#31) this one, you may read those to fix your problem. And you can insert those command at boot if you don't want to run it over and over again every time your device shutoff

**Comment by helmiau** [comment]
> > > using this script ? `/usr/sbin/openvpn --mktun --dev tun1`
> > 
> > 
> > ![16324913132904206093151101229430](https://user-images.githubusercontent.com/26756586/134685300-3607e999-90c4-487d-9e67-43be8a2d7cee.jpg)
> 
> No this is not the correct way to use that command. Those command wasn't supposed to be in the installer/compiler script since it need openvpn to be installed at a running system. For your problem it seems the same as [https://github.com/helmiau/HelmiWrt-OS/issues/31](#31) this one, you may read those to fix your problem. And you can insert those command at boot if you don't want to run it over and over again every time your device shutoff, but for the love of god don't put that on the compiler script (Makefile)

Do pull request please

**Comment by kokenot** [comment]
> > > using this script ? `/usr/sbin/openvpn --mktun --dev tun1`
> > 
> > 
> > ![16324913132904206093151101229430](https://user-images.githubusercontent.com/26756586/134685300-3607e999-90c4-487d-9e67-43be8a2d7cee.jpg)
> 
> No this is not the correct way to use that command. Those command wasn't supposed to be in the installer/compiler script since it need openvpn to be installed at a running system. For your problem it seems the same as [https://github.com/helmiau/HelmiWrt-OS/issues/31](#31) this one, you may read those to fix your problem. And you can insert those command at boot if you don't want to run it over and over again every time your device shutoff, but for the love of god don't put that on the compiler script (Makefile)

i can't click the link. no

**Comment by kokenot** [comment]
thanks i will look into it
