### ISSUE TITLE
menu luci-app-llibernet-plus gak tampil cuma blank background di v 1.8, aman di v 1.6

### ISSUE THREAD

**Issue by uHash64** [helmiau/helmiwrt-packages#9]

**Comment by uHash64** [comment]
pakai fw ini
19.07.8 https://github.com/uHash64/amlogic-s9xxx-openwrt/releases/download/openwrt_s9xxx_official_2022.01.19.1558/openwrt_s905x_k5.4.172_2022.01.19.1557.img.gz

**Comment by helmiau** [comment]
kasih info yang lengkap plis, ane ga paham maksudnya

**Comment by uHash64** [comment]
![ss](https://user-images.githubusercontent.com/86231744/150226878-cd86f170-8f64-4b85-8eaf-f69d57321d59.png)

gini kalau pakai versi 1.8

**Comment by helmiau** [comment]
di ane aman kok bang

**Comment by helmiau** [comment]
coba ganti browser, clear cache browser
